//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseSchool {
    
    
    public partial class User {
        
        /// <summary>
        /// ctrlUserInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ChineseSchool.UserControl.UC_UserInfo ctrlUserInfo;
        
        /// <summary>
        /// ctrlChildren control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ChineseSchool.UserControl.UC_ChildList ctrlChildren;
    }
}
